-- MySQL Script generated by MySQL Workbench
-- 03/30/16 13:35:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema VA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VA` DEFAULT CHARACTER SET utf8 ;
USE `VA` ;

-- -----------------------------------------------------
-- Table `VA`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Administrador` (
  `Usuario` VARCHAR(45) NOT NULL,
  `Contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Grado` (
  `Nro_grado` INT NOT NULL,
  `Cantidad` INT NULL,
  PRIMARY KEY (`Nro_grado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Alumno` (
  `DNI_Alumno` INT NOT NULL,
  `NombreApellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Grado_Nro_grado` INT NOT NULL,
  PRIMARY KEY (`DNI_Alumno`),
  INDEX `fk_Alumno_Grado1_idx` (`Grado_Nro_grado` ASC),
  CONSTRAINT `fk_Alumno_Grado1`
    FOREIGN KEY (`Grado_Nro_grado`)
    REFERENCES `VA`.`Grado` (`Nro_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Otro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Otro` (
  `idOtro` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NULL,
  `Descripcion` VARCHAR(1000) NULL,
  `Alumno_DNI_Alumno` INT NOT NULL,
  PRIMARY KEY (`idOtro`),
  INDEX `fk_Otro_Alumno1_idx` (`Alumno_DNI_Alumno` ASC),
  CONSTRAINT `fk_Otro_Alumno1`
    FOREIGN KEY (`Alumno_DNI_Alumno`)
    REFERENCES `VA`.`Alumno` (`DNI_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Avisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Avisos` (
  `idAvisos` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NULL,
  `Descripcion` VARCHAR(1000) NULL,
  `Alumno_DNI_Alumno` INT NOT NULL,
  PRIMARY KEY (`idAvisos`),
  INDEX `fk_Avisos_Alumno1_idx` (`Alumno_DNI_Alumno` ASC),
  CONSTRAINT `fk_Avisos_Alumno1`
    FOREIGN KEY (`Alumno_DNI_Alumno`)
    REFERENCES `VA`.`Alumno` (`DNI_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Padre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Padre` (
  `DNI_padre` INT NOT NULL,
  `NombreApellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  PRIMARY KEY (`DNI_padre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Alumno/Padre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Alumno/Padre` (
  `Alumno_DNI_Alumno` INT NOT NULL,
  `Padre_DNI_padre` INT NOT NULL,
  PRIMARY KEY (`Alumno_DNI_Alumno`, `Padre_DNI_padre`),
  INDEX `fk_Alumno_has_Padre_Padre1_idx` (`Padre_DNI_padre` ASC),
  INDEX `fk_Alumno_has_Padre_Alumno_idx` (`Alumno_DNI_Alumno` ASC),
  CONSTRAINT `fk_Alumno_has_Padre_Alumno`
    FOREIGN KEY (`Alumno_DNI_Alumno`)
    REFERENCES `VA`.`Alumno` (`DNI_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Padre_Padre1`
    FOREIGN KEY (`Padre_DNI_padre`)
    REFERENCES `VA`.`Padre` (`DNI_padre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Docente` (
  `DNI_docente` INT NOT NULL,
  `NombreApellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  PRIMARY KEY (`DNI_docente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Materia` (
  `Cod_materia` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Contenido` VARCHAR(45) NULL,
  `Grado_Nro_grado` INT NOT NULL,
  PRIMARY KEY (`Cod_materia`),
  INDEX `fk_Materia_Grado1_idx` (`Grado_Nro_grado` ASC),
  CONSTRAINT `fk_Materia_Grado1`
    FOREIGN KEY (`Grado_Nro_grado`)
    REFERENCES `VA`.`Grado` (`Nro_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Tareas` (
  `idTareas` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NULL,
  `Fecha_entrega_tarea` DATE NULL,
  `Descripcion` VARCHAR(1000) NULL,
  `Correccion` VARCHAR(1000) NULL,
  `Materia_Cod_materia` INT NOT NULL,
  PRIMARY KEY (`idTareas`),
  INDEX `fk_Tareas_Materia1_idx` (`Materia_Cod_materia` ASC),
  CONSTRAINT `fk_Tareas_Materia1`
    FOREIGN KEY (`Materia_Cod_materia`)
    REFERENCES `VA`.`Materia` (`Cod_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Examen` (
  `idExamen` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NULL,
  `Fecha_examen` DATE NULL,
  `Descripcion` VARCHAR(1000) NULL,
  `Nota` REAL NULL,
  `Materia_Cod_materia` INT NOT NULL,
  PRIMARY KEY (`idExamen`),
  INDEX `fk_Examen_Materia1_idx` (`Materia_Cod_materia` ASC),
  CONSTRAINT `fk_Examen_Materia1`
    FOREIGN KEY (`Materia_Cod_materia`)
    REFERENCES `VA`.`Materia` (`Cod_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Practicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Practicos` (
  `idPracticos` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NULL,
  `Descripcion` VARCHAR(1000) NULL,
  `Resultado` VARCHAR(100) NULL,
  `Fecha_entrega_practico` DATE NULL,
  `Materia_Cod_materia` INT NOT NULL,
  PRIMARY KEY (`idPracticos`),
  INDEX `fk_Practicos_Materia1_idx` (`Materia_Cod_materia` ASC),
  CONSTRAINT `fk_Practicos_Materia1`
    FOREIGN KEY (`Materia_Cod_materia`)
    REFERENCES `VA`.`Materia` (`Cod_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VA`.`Grado_has_Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VA`.`Grado_has_Docente` (
  `Grado_Nro_grado` INT NOT NULL,
  `Docente_DNI_docente` INT NOT NULL,
  PRIMARY KEY (`Grado_Nro_grado`, `Docente_DNI_docente`),
  INDEX `fk_Grado_has_Docente_Docente1_idx` (`Docente_DNI_docente` ASC),
  INDEX `fk_Grado_has_Docente_Grado1_idx` (`Grado_Nro_grado` ASC),
  CONSTRAINT `fk_Grado_has_Docente_Grado1`
    FOREIGN KEY (`Grado_Nro_grado`)
    REFERENCES `VA`.`Grado` (`Nro_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grado_has_Docente_Docente1`
    FOREIGN KEY (`Docente_DNI_docente`)
    REFERENCES `VA`.`Docente` (`DNI_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
